name: Java CI
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-test-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#      - name: Build and push
#        uses: docker/build-push-action@v4.0.0
#        uses: mr-smithers-excellent/docker-build-push@v5
#        with:
#          push: false
#          tags: clayder/cidd-demo-java:latest

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: peterclayder/cidd-demo-java:latest
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


#      - name: Docker login
#        uses: docker/login-action@v1
#        with:
#          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build And Push Docker Image
#        env:
#          DOCKER_REPOSITORY_PATH: ${{ secrets.DOCKER_REPOSITORY_PATH }}
#          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
#          TESTCONTAINERS_RYUK_DISABLED: true
#        run: |
#          export DOCKER_IMAGE=`echo "${DOCKER_REGISTRY_URL}/${DOCKER_REPOSITORY_PATH}/ciCdDemo" | sed -e 's#//#/#' -e 's#^/##'`
#          ./mvnw deploy -Dpackaging=docker -Djib.docker.image=$DOCKER_IMAGE --no-transfer-progress
